# -*- coding: utf-8 -*-
"""TCC_MBA_working_vers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qNwO2Wl8SMDF5Rv4YB0pPkXWGqhLc1mJ

# Instalando pacotes
"""

# !pip install --quiet duckdb
# !pip install --quiet jupysql
# !pip install --quiet duckdb-engine
# !pip install --quiet pandas
# !pip install --quiet matplotlib
# !pip install --quiet boto3
# !pip install --quiet spatial
# !pip install --quiet plotly.express
# !pip install --quiet pingouin

# !pip install --upgrade duckdb

"""# Resetando kernel e carregando pacotes"""

# Commented out IPython magic to ensure Python compatibility.
# %reset -f

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import duckdb
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, f1_score, mean_squared_error, fbeta_score, mean_absolute_error, mean_absolute_percentage_error
from datetime import date
import plotly.express as px
import plotly.graph_objects as go
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.cluster.hierarchy as sch
import scipy.stats as stats
from scipy.stats import zscore
from scipy.spatial.distance import pdist
from sklearn.cluster import AgglomerativeClustering
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
import pingouin as pg
import plotly.express as px
import plotly.io as pio
pio.renderers.default='browser'

pd.options.display.float_format = '{:.2f}'.format
pd.options.plotting.backend = "plotly"

# Import jupysql Jupyter extension to create SQL cells
# %load_ext sql

# some DuckDB setup
con = duckdb.connect(':default:')
# enable automatic query parallelization
con.execute("PRAGMA threads=2")
# enable caching of parquet metadata
con.execute("PRAGMA enable_object_cache")

# Commented out IPython magic to ensure Python compatibility.
# %config SqlMagic.autopandas = True
# %config SqlMagic.feedback = False
# %config SqlMagic.displaycon = False
# %sql con

from google.colab import drive
drive.mount('/content/drive')

"""# carregando os arquivos"""

pib_excel = pd.read_excel('/content/drive/MyDrive/MBA_DSA/TCC/PIB dos Munic¡pios - base de dados 2010-2021.xlsx')

pib_excel.head(10)

unidades_empresas = pd.read_excel('/content/drive/MyDrive/MBA_DSA/TCC/cadastro_empresas_maiores_municipios_com_codigo.xlsx',sheet_name='numero_unidades')

unidades_empresas.head(10)

pessoal_ocupado_empresas = pd.read_excel('/content/drive/MyDrive/MBA_DSA/TCC/cadastro_empresas_maiores_municipios_com_codigo.xlsx',sheet_name='pessoal_ocupado')

pessoal_ocupado_empresas.head(10)

pib_total = pd.read_excel('/content/drive/MyDrive/MBA_DSA/TCC/pibs_municipais.xlsx',sheet_name='pib_total')

pib_total.head(10)

pib_impostos = pd.read_excel('/content/drive/MyDrive/MBA_DSA/TCC/pibs_municipais.xlsx',sheet_name='impostos')

pib_impostos.head(10)

valor_adicionado_total = pd.read_excel('/content/drive/MyDrive/MBA_DSA/TCC/pibs_municipais.xlsx',sheet_name='valor_adicionado_total')

valor_adicionado_total.head(10)

valor_agri = pd.read_excel('/content/drive/MyDrive/MBA_DSA/TCC/pibs_municipais.xlsx',sheet_name='valor_agri')

valor_agri.head(10)

valor_industria = pd.read_excel('/content/drive/MyDrive/MBA_DSA/TCC/pibs_municipais.xlsx',sheet_name='valor_industria')

valor_industria.head(10)

valor_servicos = pd.read_excel('/content/drive/MyDrive/MBA_DSA/TCC/pibs_municipais.xlsx',sheet_name='valor_servicos')

valor_servicos.head(10)

valor_adm = pd.read_excel('/content/drive/MyDrive/MBA_DSA/TCC/pibs_municipais.xlsx',sheet_name='valor_adm')

valor_adm.head(10)

cidades = pd.read_csv('/content/drive/MyDrive/MBA_DSA/TCC/entes.csv')

cidades.head(10)

df_analise = cidades.query('esfera == "M"')[['cod_ibge','ente','regiao','uf','populacao']]

df_analise

valor_agri

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# 
# select count(da.cod_ibge),count(vagr.cod_ibge),count(vadm.cod_ibge),count(vind.cod_ibge),count(vserv.cod_ibge) from df_analise da
# inner join valor_agri vagr on vagr.cod_ibge = da.cod_ibge
# inner join pib_impostos imp on imp.cod_ibge = da.cod_ibge
# inner join valor_adm vadm on vadm.cod_ibge = da.cod_ibge
# inner join valor_industria vind on vind.cod_ibge = da.cod_ibge
# inner join valor_servicos vserv on vserv.cod_ibge = da.cod_ibge
# inner join valor_adicionado_total vadd on vadd.cod_ibge = da.cod_ibge

df_analise

df_analise = cidades.query('esfera == "M"')[['cod_ibge','ente','regiao','uf','populacao']]

df_analise = df_analise.merge(pib_total[['cod_ibge','2021']], on= 'cod_ibge')
df_analise.rename(columns={'2021': 'pib_total'},inplace=True)
df_analise.head(5)

df_analise = df_analise.merge(pib_impostos[['cod_ibge','2021']], on= 'cod_ibge')
df_analise.rename(columns={'2021': 'pib_impostos'},inplace=True)
df_analise.head(5)

df_analise = df_analise.merge(valor_adm[['cod_ibge','2021']], on= 'cod_ibge')
df_analise.rename(columns={'2021': 'valor_adm'},inplace=True)
df_analise.head(5)

valor_industria.columns

valor_industria[['cod_ibge',2021]]

df_analise = df_analise.merge(valor_industria[['cod_ibge',2021]], on= 'cod_ibge')
df_analise.rename(columns={2021: 'valor_industria'},inplace=True)
df_analise.head(5)

df_analise = df_analise.merge(valor_servicos[['cod_ibge',2021]], on= 'cod_ibge')
df_analise.rename(columns={2021: 'valor_servicos'},inplace=True)
df_analise.head(5)

df_analise = df_analise.merge(valor_adicionado_total[['cod_ibge','2021']], on= 'cod_ibge')
df_analise.rename(columns={'2021': 'valor_adicionado_total'},inplace=True)
df_analise.head(5)

df_analise = df_analise.merge(valor_agri[['cod_ibge',2021]], on= 'cod_ibge')
df_analise.rename(columns={2021: 'valor_agri'},inplace=True)
df_analise.head(5)

df_analise['pib_p_capita']=round(df_analise['pib_total']/df_analise['populacao'],2)

df_analise

RREO = pd.read_csv('/content/drive/MyDrive/MBA_DSA/TCC/RREO_COMBINADO.csv')

RREO.columns

df_RREO = RREO.query("exercicio == 2021 and conta == 'TOTAL (III) = (I + II)' and coluna == 'DOTAÇÃO INICIAL'")[['cod_ibge','valor']]
df_RREO.rename(columns={'valor': 'valor_inicial'},inplace=True)
df_RREO.head(5)

df_RREO['valor_atualizado'] = RREO.query("exercicio == 2021 and conta == 'TOTAL (III) = (I + II)' and coluna == 'DOTAÇÃO ATUALIZADA (a)'")['valor'].values
df_RREO.head(5)

df_RREO.reset_index()

df_RREO['erro_planejamento'] = df_RREO['valor_atualizado']/df_RREO['valor_inicial'] - 1

cidades.query('cod_ibge == 2706703 or cod_ibge == 2112852')

df_RREO

"""# Clusterizações

## Total, Populacao e PIB

df_cluster abaixo já não incluirá os casos onde não encontramos o RREO
"""

df_analise_com_erro = df_analise.merge(df_RREO[['cod_ibge','erro_planejamento']], on = 'cod_ibge')

df_analise_com_erro.columns

df_cluster = df_analise_com_erro[['erro_planejamento','populacao','pib_total']]

silhueta = []
I = range(2,9) # ponto de parada pode ser parametrizado manualmente
for i in I:
    kmeansSil = KMeans(n_clusters=i, init='random', random_state=100).fit(df_cluster)
    silhueta.append(silhouette_score(df_cluster, kmeansSil.labels_))

plt.figure(figsize=(16,8))
plt.plot(range(2, 9), silhueta, color = 'purple', marker='o') # Ajustar range
plt.xlabel('Nº Clusters', fontsize=16)
plt.ylabel('Silhueta Média', fontsize=16)
plt.title('Método da Silhueta', fontsize=16)
plt.axvline(x = silhueta.index(max(silhueta))+2, linestyle = 'dotted', color = 'red')
plt.show()



kmeans_erro = KMeans(n_clusters=5, init='random', random_state=100).fit(df_cluster)

# Criando a variável que indica os clusters no banco de dados

kmeans_clusters = kmeans_erro.labels_
df_analise_com_erro['cluster_kmeans'] = kmeans_clusters
df_analise_com_erro['cluster_kmeans'] = df_analise_com_erro['cluster_kmeans'].astype('category')
## O padrão dos clusters é o mesmo dos métodos hierárquicos anteriores

df_analise_com_erro

df_analise_com_erro.columns

cent_finais = pd.DataFrame(kmeans_erro.cluster_centers_)
cent_finais.columns = df_cluster.columns
cent_finais.index.name = 'cluster'
cent_finais

df_analise_com_erro.groupby('cluster_kmeans').describe()

df_analise_com_erro.groupby(by= 'cluster_kmeans')[['erro_planejamento','pib_total']].describe()

df_analise_com_erro.groupby(by= 'cluster_kmeans')[['erro_planejamento','populacao']].describe()

plt.figure(figsize=(10,10))
sns.scatterplot(x='erro_planejamento', y='pib_total', data=df_analise_com_erro, hue='cluster_kmeans', palette='viridis', s=100)
sns.scatterplot(x='erro_planejamento', y='pib_total', data=cent_finais, s=40, c='red', label='Centroides', marker="X")
plt.title('Clusters e centroides', fontsize=16)
plt.xlabel('Erro Planejamento Total', fontsize=16)
plt.ylabel('PIB total', fontsize=16)
plt.legend()
plt.show()

"""# Per Capita"""



df_analise_com_erro = df_analise.merge(df_RREO[['cod_ibge','erro_planejamento']], on = 'cod_ibge')

df_analise_com_erro.columns

df_cluster = df_analise_com_erro[['erro_planejamento','pib_p_capita']]

silhueta = []
I = range(2,9) # ponto de parada pode ser parametrizado manualmente
for i in I:
    kmeansSil = KMeans(n_clusters=i, init='random', random_state=100).fit(df_cluster)
    silhueta.append(silhouette_score(df_cluster, kmeansSil.labels_))

plt.figure(figsize=(16,8))
plt.plot(range(2, 9), silhueta, color = 'purple', marker='o') # Ajustar range
plt.xlabel('Nº Clusters', fontsize=16)
plt.ylabel('Silhueta Média', fontsize=16)
plt.title('Método da Silhueta', fontsize=16)
plt.axvline(x = silhueta.index(max(silhueta))+2, linestyle = 'dotted', color = 'red')
plt.show()



kmeans_erro = KMeans(n_clusters=4, init='random', random_state=100).fit(df_cluster)

# Criando a variável que indica os clusters no banco de dados

kmeans_clusters = kmeans_erro.labels_
df_analise_com_erro['cluster_kmeans'] = kmeans_clusters
df_analise_com_erro['cluster_kmeans'] = df_analise_com_erro['cluster_kmeans'].astype('category')
## O padrão dos clusters é o mesmo dos métodos hierárquicos anteriores

df_analise_com_erro

df_analise_com_erro.columns

cent_finais = pd.DataFrame(kmeans_erro.cluster_centers_)
cent_finais.columns = df_cluster.columns
cent_finais.index.name = 'cluster'
cent_finais

df_analise_com_erro.groupby('cluster_kmeans').describe()

df_analise_com_erro.groupby(by= 'cluster_kmeans')[['erro_planejamento','pib_p_capita']].describe()

# df_analise_com_erro.groupby(by= 'cluster_kmeans')[['erro_planejamento','populacao']].describe()

plt.figure(figsize=(10,10))
sns.scatterplot(x='erro_planejamento', y='pib_p_capita', data=df_analise_com_erro, hue='cluster_kmeans', palette='viridis', s=100)
sns.scatterplot(x='erro_planejamento', y='pib_p_capita', data=cent_finais, s=40, c='red', label='Centroides', marker="X")
plt.title('Clusters e centroides', fontsize=16)
plt.xlabel('Erro Planejamento Total', fontsize=16)
plt.ylabel('PIB per capita', fontsize=16)
plt.legend()
plt.show()

assert False

"""## Total, somente população abaixo de 50000"""

df_RREO.columns

df_analise_com_erro = df_analise.query('populacao < 50000').merge(df_RREO[['cod_ibge','erro_planejamento']], on = 'cod_ibge')

df_analise_com_erro.columns

df_cluster = df_analise_com_erro[['erro_planejamento','populacao','pib_total']]

silhueta = []
I = range(2,9) # ponto de parada pode ser parametrizado manualmente
for i in I:
    kmeansSil = KMeans(n_clusters=i, init='random', random_state=100).fit(df_cluster)
    silhueta.append(silhouette_score(df_cluster, kmeansSil.labels_))

plt.figure(figsize=(16,8))
plt.plot(range(2, 9), silhueta, color = 'purple', marker='o') # Ajustar range
plt.xlabel('Nº Clusters', fontsize=16)
plt.ylabel('Silhueta Média', fontsize=16)
plt.title('Método da Silhueta', fontsize=16)
plt.axvline(x = silhueta.index(max(silhueta))+2, linestyle = 'dotted', color = 'red')
plt.show()



kmeans_erro = KMeans(n_clusters=5, init='random', random_state=100).fit(df_cluster)

# Criando a variável que indica os clusters no banco de dados

kmeans_clusters = kmeans_erro.labels_
df_analise_com_erro['cluster_kmeans'] = kmeans_clusters
df_analise_com_erro['cluster_kmeans'] = df_analise_com_erro['cluster_kmeans'].astype('category')
## O padrão dos clusters é o mesmo dos métodos hierárquicos anteriores

df_analise_com_erro

df_analise_com_erro.columns

cent_finais = pd.DataFrame(kmeans_erro.cluster_centers_)
cent_finais.columns = df_cluster.columns
cent_finais.index.name = 'cluster'
cent_finais

df_analise_com_erro.groupby('cluster_kmeans').describe()

df_analise_com_erro.groupby(by= 'cluster_kmeans')[['erro_planejamento','pib_total']].describe()

df_analise_com_erro.groupby(by= 'cluster_kmeans')[['erro_planejamento','populacao']].describe()

plt.figure(figsize=(10,10))
sns.scatterplot(x='erro_planejamento', y='pib_total', data=df_analise_com_erro, hue='cluster_kmeans', palette='viridis', s=100)
sns.scatterplot(x='erro_planejamento', y='pib_total', data=cent_finais, s=40, c='red', label='Centroides', marker="X")
plt.title('Clusters e centroides', fontsize=16)
plt.xlabel('Erro Planejamento Total', fontsize=16)
plt.ylabel('PIB Total', fontsize=16)
plt.legend()
plt.show()

plt.figure(figsize=(10,10))
sns.scatterplot(x='erro_planejamento', y='populacao', data=df_analise_com_erro, hue='cluster_kmeans', palette='viridis', s=100)
sns.scatterplot(x='erro_planejamento', y='populacao', data=cent_finais, s=40, c='red', label='Centroides', marker="X")
plt.title('Clusters e centroides', fontsize=16)
plt.xlabel('Erro Planejamento Total', fontsize=16)
plt.ylabel('Populacao', fontsize=16)
plt.legend()
plt.show()

plt.figure(figsize=(10,10))
sns.scatterplot(x='pib_total', y='populacao', data=df_analise_com_erro, hue='cluster_kmeans', palette='viridis', s=100)
sns.scatterplot(x='pib_total', y='populacao', data=cent_finais, s=40, c='red', label='Centroides', marker="X")
plt.title('Clusters e centroides', fontsize=16)
plt.xlabel('PIB Total', fontsize=16)
plt.ylabel('Populacao', fontsize=16)
plt.legend()
plt.show()

assert False

"""## Total, somente população acima de 50000"""



df_RREO.columns

df_analise_com_erro = df_analise.query('populacao > 50000').merge(df_RREO[['cod_ibge','erro_planejamento']], on = 'cod_ibge')

df_analise_com_erro.columns

df_cluster = df_analise_com_erro[['erro_planejamento','populacao','pib_total']]

silhueta = []
I = range(2,9) # ponto de parada pode ser parametrizado manualmente
for i in I:
    kmeansSil = KMeans(n_clusters=i, init='random', random_state=100).fit(df_cluster)
    silhueta.append(silhouette_score(df_cluster, kmeansSil.labels_))

plt.figure(figsize=(16,8))
plt.plot(range(2, 9), silhueta, color = 'purple', marker='o') # Ajustar range
plt.xlabel('Nº Clusters', fontsize=16)
plt.ylabel('Silhueta Média', fontsize=16)
plt.title('Método da Silhueta', fontsize=16)
plt.axvline(x = silhueta.index(max(silhueta))+2, linestyle = 'dotted', color = 'red')
plt.show()



kmeans_erro = KMeans(n_clusters=5, init='random', random_state=100).fit(df_cluster)

# Criando a variável que indica os clusters no banco de dados

kmeans_clusters = kmeans_erro.labels_
df_analise_com_erro['cluster_kmeans'] = kmeans_clusters
df_analise_com_erro['cluster_kmeans'] = df_analise_com_erro['cluster_kmeans'].astype('category')
## O padrão dos clusters é o mesmo dos métodos hierárquicos anteriores

df_analise_com_erro

df_analise_com_erro.columns

cent_finais = pd.DataFrame(kmeans_erro.cluster_centers_)
cent_finais.columns = df_cluster.columns
cent_finais.index.name = 'cluster'
cent_finais

df_analise_com_erro.groupby('cluster_kmeans').describe()

df_analise_com_erro.groupby(by= 'cluster_kmeans')[['erro_planejamento','pib_total']].describe()

df_analise_com_erro.groupby(by= 'cluster_kmeans')[['erro_planejamento','populacao']].describe()

plt.figure(figsize=(10,10))
sns.scatterplot(x='erro_planejamento', y='pib_total', data=df_analise_com_erro, hue='cluster_kmeans', palette='viridis', s=100)
sns.scatterplot(x='erro_planejamento', y='pib_total', data=cent_finais, s=40, c='red', label='Centroides', marker="X")
plt.title('Clusters e centroides', fontsize=16)
plt.xlabel('Erro Planejamento Total', fontsize=16)
plt.ylabel('PIB total', fontsize=16)
plt.legend()
plt.show()

plt.figure(figsize=(10,10))
sns.scatterplot(x='erro_planejamento', y='populacao', data=df_analise_com_erro, hue='cluster_kmeans', palette='viridis', s=100)
sns.scatterplot(x='erro_planejamento', y='populacao', data=cent_finais, s=40, c='red', label='Centroides', marker="X")
plt.title('Clusters e centroides', fontsize=16)
plt.xlabel('Erro Planejamento Total', fontsize=16)
plt.ylabel('Populacao', fontsize=16)
plt.legend()
plt.show()

plt.figure(figsize=(10,10))
sns.scatterplot(x='pib_total', y='populacao', data=df_analise_com_erro, hue='cluster_kmeans', palette='viridis', s=100)
sns.scatterplot(x='pib_total', y='populacao', data=cent_finais, s=40, c='red', label='Centroides', marker="X")
plt.title('Clusters e centroides', fontsize=16)
plt.xlabel('PIB Total', fontsize=16)
plt.ylabel('Populacao', fontsize=16)
plt.legend()
plt.show()