# -*- coding: utf-8 -*-
"""TCC_MBA_transformando_em_python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jgcplQAyr-S694Hz3RoeR-1lGeVaztEB

# Instalando pacotes

# Resetando kernel e carregando pacotes
"""

# Commented out IPython magic to ensure Python compatibility.
# %reset -f

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, f1_score, mean_squared_error, fbeta_score, mean_absolute_error, mean_absolute_percentage_error
from datetime import date
import plotly.express as px
import plotly.graph_objects as go
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.cluster.hierarchy as sch
import scipy.stats as stats
from scipy.stats import zscore
from scipy.spatial.distance import pdist
from sklearn.cluster import AgglomerativeClustering
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
import pingouin as pg
import plotly.express as px
import plotly.io as pio
import os
pio.renderers.default='browser'

pd.options.display.float_format = '{:.2f}'.format
pd.options.plotting.backend = "plotly"

def plot_scatter_combinations(df, save_dir='graficos_todas_as_var_3cluster',numero_clusters=4):
    # Create the directory if it doesn't exist
    if not os.path.exists(save_dir):
        os.makedirs(save_dir)
    df_funcao = df[:]
    # Select the first five columns
    columns = df.columns

    silhueta = []
    I = range(2,9) # ponto de parada pode ser parametrizado manualmente
    for i in I:
        kmeansSil = KMeans(n_clusters=i, init='random', random_state=100).fit(df_funcao)
        silhueta.append(silhouette_score(df_funcao, kmeansSil.labels_))

    plt.figure(figsize=(16,8))
    plt.plot(range(2, 9), silhueta, color = 'purple', marker='o') # Ajustar range
    plt.xlabel('Nº Clusters', fontsize=16)
    plt.ylabel('Silhueta Média', fontsize=16)
    plt.title('Método da Silhueta', fontsize=16)
    plt.axvline(x = silhueta.index(max(silhueta))+2, linestyle = 'dotted', color = 'red')
    # Save the plot
    plot_filename = os.path.join(save_dir, f'silhueta_teste.png')
    plt.savefig(plot_filename)
    plt.close()

    kmeans_erro = KMeans(n_clusters=numero_clusters, init='random', random_state=100).fit(df_funcao)

    # Criando a variável que indica os clusters no banco de dados

    kmeans_clusters = kmeans_erro.labels_
    df['cluster_kmeans'] = kmeans_clusters
    df['cluster_kmeans'] = df['cluster_kmeans'].astype('category')
    cent_finais = pd.DataFrame(kmeans_erro.cluster_centers_)
    cent_finais.columns = df_funcao.columns
    cent_finais.index.name = 'cluster'
    


    # sns.scatterplot(x='erro_planejamento', y='pib_total', data=cent_finais, s=40, c='red', label='Centroides', marker="X")
    # plt.title('Clusters e centroides', fontsize=16)
    # plt.xlabel('Erro Planejamento Total', fontsize=16)
    # plt.ylabel('PIB Total', fontsize=16)
    # plt.legend()
    # plt.show()
    # Loop through the combinations of columns
    for i in range(len(columns)):
        for j in range(i + 1, len(columns)):
            # Create scatter plot
            plt.figure(figsize=(10,10))
            sns.scatterplot(x=df[columns[i]], y=df[columns[j]],data=df,hue='cluster_kmeans', palette='viridis', s=100)
            plt.title(f'plot de {columns[i]} vs {columns[j]}')
            plt.xlabel(columns[i])
            plt.ylabel(columns[j])
            
            # Save the plot
            plot_filename = os.path.join(save_dir, f'{columns[i]}_{columns[j]}.png')
            plt.savefig(plot_filename)
            plt.close()

"""# carregando os arquivos"""

pib_excel = pd.read_excel('/Users/gustavooliveiracoelho/hello/pibs/PIB dos Munic¡pios - base de dados 2010-2021.xlsx')

print(pib_excel.head(3))

unidades_empresas = pd.read_excel('/Users/gustavooliveiracoelho/hello/pibs/cadastro_empresas_maiores_municipios_com_codigo.xlsx',sheet_name='numero_unidades')

print(unidades_empresas.head(3))

pessoal_ocupado_empresas = pd.read_excel('/Users/gustavooliveiracoelho/hello/pibs/cadastro_empresas_maiores_municipios_com_codigo.xlsx',sheet_name='pessoal_ocupado')

print(pessoal_ocupado_empresas.head(3))

pib_total = pd.read_excel('/Users/gustavooliveiracoelho/hello/pibs/pibs_municipais.xlsx',sheet_name='pib_total')

print(pib_total.head(3))

pib_impostos = pd.read_excel('/Users/gustavooliveiracoelho/hello/pibs/pibs_municipais.xlsx',sheet_name='impostos')

print(pib_impostos.head(3))

valor_adicionado_total = pd.read_excel('/Users/gustavooliveiracoelho/hello/pibs/pibs_municipais.xlsx',sheet_name='valor_adicionado_total')

print(valor_adicionado_total.head(3))

valor_agri = pd.read_excel('/Users/gustavooliveiracoelho/hello/pibs/pibs_municipais.xlsx',sheet_name='valor_agri')

print(valor_agri.head(3))

valor_industria = pd.read_excel('/Users/gustavooliveiracoelho/hello/pibs/pibs_municipais.xlsx',sheet_name='valor_industria')

print(valor_industria.head(3))

valor_servicos = pd.read_excel('/Users/gustavooliveiracoelho/hello/pibs/pibs_municipais.xlsx',sheet_name='valor_servicos')

print(valor_servicos.head(3))

valor_adm = pd.read_excel('/Users/gustavooliveiracoelho/hello/pibs/pibs_municipais.xlsx',sheet_name='valor_adm')

print(valor_adm.head(3))

cidades = pd.read_csv('/Users/gustavooliveiracoelho/hello/pibs/entes.csv')

print(cidades.head(3))

df_analise = cidades.query('esfera == "M"')[['cod_ibge','ente','regiao','uf','populacao']]

print(df_analise.head(3))

df_analise = cidades.query('esfera == "M"')[['cod_ibge','ente','regiao','uf','populacao']]

df_analise = df_analise.merge(pib_total[['cod_ibge','2021']], on= 'cod_ibge')
df_analise.rename(columns={'2021': 'pib_total'},inplace=True)
df_analise['pib_total_pcapita'] = round(df_analise['pib_total']/df_analise['populacao'],2)
print(df_analise.head(3))

df_analise = df_analise.merge(pib_impostos[['cod_ibge','2021']], on= 'cod_ibge')
df_analise.rename(columns={'2021': 'pib_impostos'},inplace=True)
df_analise['pib_impostos_pcapita'] = round(df_analise['pib_impostos']/df_analise['populacao'],2)
print(df_analise.head(3))

df_analise = df_analise.merge(valor_adm[['cod_ibge','2021']], on= 'cod_ibge')
df_analise.rename(columns={'2021': 'pib_adm'},inplace=True)
df_analise['pib_adm_pcapita'] = round(df_analise['pib_adm']/df_analise['populacao'],2)
print(df_analise.head(3))

print(valor_industria.columns)

df_analise = df_analise.merge(valor_industria[['cod_ibge',2021]], on= 'cod_ibge')
df_analise.rename(columns={2021: 'pib_industria'},inplace=True)
df_analise['pib_industria_pcapita'] = round(df_analise['pib_industria']/df_analise['populacao'],2)
print(df_analise.head(3))

df_analise = df_analise.merge(valor_servicos[['cod_ibge',2021]], on= 'cod_ibge')
df_analise.rename(columns={2021: 'pib_servicos'},inplace=True)
df_analise['pib_servicos_pcapita'] = round(df_analise['pib_servicos']/df_analise['populacao'],2)
print(df_analise.head(3))

df_analise = df_analise.merge(valor_adicionado_total[['cod_ibge','2021']], on= 'cod_ibge')
df_analise.rename(columns={'2021': 'pib_adicionado'},inplace=True)
df_analise['pib_adicionado_pcapita'] = round(df_analise['pib_adicionado']/df_analise['populacao'],2)
print(df_analise.head(3))

df_analise = df_analise.merge(valor_agri[['cod_ibge',2021]], on= 'cod_ibge')
df_analise.rename(columns={2021: 'pib_agri'},inplace=True)
df_analise['pib_agri_pcapita'] = round(df_analise['pib_agri']/df_analise['populacao'],2)
print(df_analise.head(3))


print(df_analise.head(3))

RREO = pd.read_csv('/Users/gustavooliveiracoelho/hello/pibs/RREO_COMBINADO.csv')

print(RREO.columns)

df_RREO = RREO.query("exercicio == 2021 and conta == 'TOTAL (III) = (I + II)' and coluna == 'DOTAÇÃO INICIAL'")[['cod_ibge','valor']]
df_RREO.rename(columns={'valor': 'valor_inicial'},inplace=True)
print(df_RREO.head(3))

df_RREO['valor_atualizado'] = RREO.query("exercicio == 2021 and conta == 'TOTAL (III) = (I + II)' and coluna == 'DOTAÇÃO ATUALIZADA (a)'")['valor'].values
print(df_RREO.head(3))

df_RREO['erro_planejamento'] = df_RREO['valor_atualizado']/df_RREO['valor_inicial'] - 1

cidades.query('cod_ibge == 2706703 or cod_ibge == 2112852')

# print(df_RREO.head(3))

"""# Clusterizações

## Total, Populacao e PIB

df_cluster abaixo já não incluirá os casos onde não encontramos o RREO
"""

df_analise_com_erro = df_analise.merge(df_RREO[['cod_ibge','erro_planejamento']], on = 'cod_ibge')

print(df_analise_com_erro.columns)

df_cluster = df_analise_com_erro.query('erro_planejamento < 30')[['erro_planejamento','pib_total',
       'pib_total_pcapita', 'pib_impostos', 'pib_impostos_pcapita', 'pib_adm',
       'pib_adm_pcapita', 'pib_industria', 'pib_industria_pcapita',
       'pib_servicos', 'pib_servicos_pcapita', 'pib_adicionado',
       'pib_adicionado_pcapita', 'pib_agri', 'pib_agri_pcapita']].apply(zscore,ddof = 1)

plot_scatter_combinations(df_cluster,save_dir='grafico_todas_5cluster',numero_clusters=5)

# silhueta = []
# I = range(2,9) # ponto de parada pode ser parametrizado manualmente
# for i in I:
#     kmeansSil = KMeans(n_clusters=i, init='random', random_state=100).fit(df_cluster)
#     silhueta.append(silhouette_score(df_cluster, kmeansSil.labels_))

# plt.figure(figsize=(16,8))
# plt.plot(range(2, 9), silhueta, color = 'purple', marker='o') # Ajustar range
# plt.xlabel('Nº Clusters', fontsize=16)
# plt.ylabel('Silhueta Média', fontsize=16)
# plt.title('Método da Silhueta', fontsize=16)
# plt.axvline(x = silhueta.index(max(silhueta))+2, linestyle = 'dotted', color = 'red')
# plt.show()

assert False

kmeans_erro = KMeans(n_clusters=5, init='random', random_state=100).fit(df_cluster)

# Criando a variável que indica os clusters no banco de dados

kmeans_clusters = kmeans_erro.labels_
df_analise_com_erro['cluster_kmeans'] = kmeans_clusters
df_analise_com_erro['cluster_kmeans'] = df_analise_com_erro['cluster_kmeans'].astype('category')
## O padrão dos clusters é o mesmo dos métodos hierárquicos anteriores

df_analise_com_erro

df_analise_com_erro.columns

cent_finais = pd.DataFrame(kmeans_erro.cluster_centers_)
cent_finais.columns = df_cluster.columns
cent_finais.index.name = 'cluster'
cent_finais

df_analise_com_erro.groupby('cluster_kmeans').describe()

df_analise_com_erro.groupby(by= 'cluster_kmeans')[['erro_planejamento','pib_total']].describe()

df_analise_com_erro.groupby(by= 'cluster_kmeans')[['erro_planejamento','populacao']].describe()

plt.figure(figsize=(10,10))
sns.scatterplot(x='erro_planejamento', y='pib_total', data=df_analise_com_erro, hue='cluster_kmeans', palette='viridis', s=100)
sns.scatterplot(x='erro_planejamento', y='pib_total', data=cent_finais, s=40, c='red', label='Centroides', marker="X")
plt.title('Clusters e centroides', fontsize=16)
plt.xlabel('Erro Planejamento Total', fontsize=16)
plt.ylabel('PIB total', fontsize=16)
plt.legend()
plt.show()

"""# Per Capita"""



df_analise_com_erro = df_analise.merge(df_RREO[['cod_ibge','erro_planejamento']], on = 'cod_ibge')

df_analise_com_erro.columns

df_cluster = df_analise_com_erro[['erro_planejamento','pib_p_capita']]

silhueta = []
I = range(2,9) # ponto de parada pode ser parametrizado manualmente
for i in I:
    kmeansSil = KMeans(n_clusters=i, init='random', random_state=100).fit(df_cluster)
    silhueta.append(silhouette_score(df_cluster, kmeansSil.labels_))

plt.figure(figsize=(16,8))
plt.plot(range(2, 9), silhueta, color = 'purple', marker='o') # Ajustar range
plt.xlabel('Nº Clusters', fontsize=16)
plt.ylabel('Silhueta Média', fontsize=16)
plt.title('Método da Silhueta', fontsize=16)
plt.axvline(x = silhueta.index(max(silhueta))+2, linestyle = 'dotted', color = 'red')
plt.show()



kmeans_erro = KMeans(n_clusters=4, init='random', random_state=100).fit(df_cluster)

# Criando a variável que indica os clusters no banco de dados

kmeans_clusters = kmeans_erro.labels_
df_analise_com_erro['cluster_kmeans'] = kmeans_clusters
df_analise_com_erro['cluster_kmeans'] = df_analise_com_erro['cluster_kmeans'].astype('category')
## O padrão dos clusters é o mesmo dos métodos hierárquicos anteriores

df_analise_com_erro

df_analise_com_erro.columns

cent_finais = pd.DataFrame(kmeans_erro.cluster_centers_)
cent_finais.columns = df_cluster.columns
cent_finais.index.name = 'cluster'
cent_finais

df_analise_com_erro.groupby('cluster_kmeans').describe()

df_analise_com_erro.groupby(by= 'cluster_kmeans')[['erro_planejamento','pib_p_capita']].describe()

# df_analise_com_erro.groupby(by= 'cluster_kmeans')[['erro_planejamento','populacao']].describe()

plt.figure(figsize=(10,10))
sns.scatterplot(x='erro_planejamento', y='pib_p_capita', data=df_analise_com_erro, hue='cluster_kmeans', palette='viridis', s=100)
sns.scatterplot(x='erro_planejamento', y='pib_p_capita', data=cent_finais, s=40, c='red', label='Centroides', marker="X")
plt.title('Clusters e centroides', fontsize=16)
plt.xlabel('Erro Planejamento Total', fontsize=16)
plt.ylabel('PIB per capita', fontsize=16)
plt.legend()
plt.show()

assert False

"""## Total, somente população abaixo de 50000"""

df_RREO.columns

df_analise_com_erro = df_analise.query('populacao < 50000').merge(df_RREO[['cod_ibge','erro_planejamento']], on = 'cod_ibge')

df_analise_com_erro.columns

df_cluster = df_analise_com_erro[['erro_planejamento','populacao','pib_total']]

silhueta = []
I = range(2,9) # ponto de parada pode ser parametrizado manualmente
for i in I:
    kmeansSil = KMeans(n_clusters=i, init='random', random_state=100).fit(df_cluster)
    silhueta.append(silhouette_score(df_cluster, kmeansSil.labels_))

plt.figure(figsize=(16,8))
plt.plot(range(2, 9), silhueta, color = 'purple', marker='o') # Ajustar range
plt.xlabel('Nº Clusters', fontsize=16)
plt.ylabel('Silhueta Média', fontsize=16)
plt.title('Método da Silhueta', fontsize=16)
plt.axvline(x = silhueta.index(max(silhueta))+2, linestyle = 'dotted', color = 'red')
plt.show()



kmeans_erro = KMeans(n_clusters=5, init='random', random_state=100).fit(df_cluster)

# Criando a variável que indica os clusters no banco de dados

kmeans_clusters = kmeans_erro.labels_
df_analise_com_erro['cluster_kmeans'] = kmeans_clusters
df_analise_com_erro['cluster_kmeans'] = df_analise_com_erro['cluster_kmeans'].astype('category')
## O padrão dos clusters é o mesmo dos métodos hierárquicos anteriores

df_analise_com_erro

df_analise_com_erro.columns

cent_finais = pd.DataFrame(kmeans_erro.cluster_centers_)
cent_finais.columns = df_cluster.columns
cent_finais.index.name = 'cluster'
cent_finais

df_analise_com_erro.groupby('cluster_kmeans').describe()

df_analise_com_erro.groupby(by= 'cluster_kmeans')[['erro_planejamento','pib_total']].describe()

df_analise_com_erro.groupby(by= 'cluster_kmeans')[['erro_planejamento','populacao']].describe()

plt.figure(figsize=(10,10))
sns.scatterplot(x='erro_planejamento', y='pib_total', data=df_analise_com_erro, hue='cluster_kmeans', palette='viridis', s=100)
sns.scatterplot(x='erro_planejamento', y='pib_total', data=cent_finais, s=40, c='red', label='Centroides', marker="X")
plt.title('Clusters e centroides', fontsize=16)
plt.xlabel('Erro Planejamento Total', fontsize=16)
plt.ylabel('PIB Total', fontsize=16)
plt.legend()
plt.show()

plt.figure(figsize=(10,10))
sns.scatterplot(x='erro_planejamento', y='populacao', data=df_analise_com_erro, hue='cluster_kmeans', palette='viridis', s=100)
sns.scatterplot(x='erro_planejamento', y='populacao', data=cent_finais, s=40, c='red', label='Centroides', marker="X")
plt.title('Clusters e centroides', fontsize=16)
plt.xlabel('Erro Planejamento Total', fontsize=16)
plt.ylabel('Populacao', fontsize=16)
plt.legend()
plt.show()

plt.figure(figsize=(10,10))
sns.scatterplot(x='pib_total', y='populacao', data=df_analise_com_erro, hue='cluster_kmeans', palette='viridis', s=100)
sns.scatterplot(x='pib_total', y='populacao', data=cent_finais, s=40, c='red', label='Centroides', marker="X")
plt.title('Clusters e centroides', fontsize=16)
plt.xlabel('PIB Total', fontsize=16)
plt.ylabel('Populacao', fontsize=16)
plt.legend()
plt.show()

assert False

"""## Total, somente população acima de 50000"""



df_RREO.columns

df_analise_com_erro = df_analise.query('populacao > 50000').merge(df_RREO[['cod_ibge','erro_planejamento']], on = 'cod_ibge')

df_analise_com_erro.columns

df_cluster = df_analise_com_erro[['erro_planejamento','populacao','pib_total']]

silhueta = []
I = range(2,9) # ponto de parada pode ser parametrizado manualmente
for i in I:
    kmeansSil = KMeans(n_clusters=i, init='random', random_state=100).fit(df_cluster)
    silhueta.append(silhouette_score(df_cluster, kmeansSil.labels_))

plt.figure(figsize=(16,8))
plt.plot(range(2, 9), silhueta, color = 'purple', marker='o') # Ajustar range
plt.xlabel('Nº Clusters', fontsize=16)
plt.ylabel('Silhueta Média', fontsize=16)
plt.title('Método da Silhueta', fontsize=16)
plt.axvline(x = silhueta.index(max(silhueta))+2, linestyle = 'dotted', color = 'red')
plt.show()



kmeans_erro = KMeans(n_clusters=5, init='random', random_state=100).fit(df_cluster)

# Criando a variável que indica os clusters no banco de dados

kmeans_clusters = kmeans_erro.labels_
df_analise_com_erro['cluster_kmeans'] = kmeans_clusters
df_analise_com_erro['cluster_kmeans'] = df_analise_com_erro['cluster_kmeans'].astype('category')
## O padrão dos clusters é o mesmo dos métodos hierárquicos anteriores

df_analise_com_erro

df_analise_com_erro.columns

cent_finais = pd.DataFrame(kmeans_erro.cluster_centers_)
cent_finais.columns = df_cluster.columns
cent_finais.index.name = 'cluster'
cent_finais

df_analise_com_erro.groupby('cluster_kmeans').describe()

df_analise_com_erro.groupby(by= 'cluster_kmeans')[['erro_planejamento','pib_total']].describe()

df_analise_com_erro.groupby(by= 'cluster_kmeans')[['erro_planejamento','populacao']].describe()

plt.figure(figsize=(10,10))
sns.scatterplot(x='erro_planejamento', y='pib_total', data=df_analise_com_erro, hue='cluster_kmeans', palette='viridis', s=100)
sns.scatterplot(x='erro_planejamento', y='pib_total', data=cent_finais, s=40, c='red', label='Centroides', marker="X")
plt.title('Clusters e centroides', fontsize=16)
plt.xlabel('Erro Planejamento Total', fontsize=16)
plt.ylabel('PIB total', fontsize=16)
plt.legend()
plt.show()

plt.figure(figsize=(10,10))
sns.scatterplot(x='erro_planejamento', y='populacao', data=df_analise_com_erro, hue='cluster_kmeans', palette='viridis', s=100)
sns.scatterplot(x='erro_planejamento', y='populacao', data=cent_finais, s=40, c='red', label='Centroides', marker="X")
plt.title('Clusters e centroides', fontsize=16)
plt.xlabel('Erro Planejamento Total', fontsize=16)
plt.ylabel('Populacao', fontsize=16)
plt.legend()
plt.show()

plt.figure(figsize=(10,10))
sns.scatterplot(x='pib_total', y='populacao', data=df_analise_com_erro, hue='cluster_kmeans', palette='viridis', s=100)
sns.scatterplot(x='pib_total', y='populacao', data=cent_finais, s=40, c='red', label='Centroides', marker="X")
plt.title('Clusters e centroides', fontsize=16)
plt.xlabel('PIB Total', fontsize=16)
plt.ylabel('Populacao', fontsize=16)
plt.legend()
plt.show()